#!/usr/bin/env bash

LOCAL=$HOME/.local
MAVEN_VERSION=3.6.3
GO_VERSION=1.14.2
OS=$(uname -s | tr '[:upper:]' '[:lower:]')

function setup_base() {
    [[ -d $LOCAL/bin ]] && mkdir $LOCAL/bin
    if [[ $OS == "linux" ]]; then
        sudo apt install install bat tldr ripgrep exuberant-ctags \
            tree htop git curl fzf pgcli mycli fdfind zsh tmux    #@TODO install ccls
    else
        brew install bat tldr ripgrep ctags tree htop git curl fzf \
            pgcli mycli fdfind zsh tmux ccls
    fi
}

function setup_ssh() {
    [[ ! -d $HOME/.ssh ]] && mkdir $HOME/.ssh
    ln -sf $(pwd)/ssh-config $HOME/.ssh/config
    ssh-keygen -f $HOME/.ssh/id_rsa
}

function setup_neovim() {
    python -m pip install --user pynvim && \
    python3 -m pip install --user pynvim
    NODE_PACKAGE="dockerfile-language-server-nodejs bash-language-server"
    if [[ $OS == "linux" ]]; then
        sudo npm i -g $NODE_PACKAGE
    else
        npm i -g $NODE_PACKAGE
    fi
    rm -rf ~/.vim ~/.config/nvim && \
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    ln -sf $(pwd)/nvim ~/.config/nvim
}

function setup_python() {
    PY_PACKAGE="pipenv jedi pylint"
    git clone https://github.com/pyenv/pyenv.git ~/.pyenv && \
    pip install $PY_PACKAGE
}

function setup_java() {
    MAVEN_URL=https://www-eu.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.zip
    FILENAME=$(basename $MAVEN_URL)
    curl -LO $MAVEN_URL && \
    unzip $FILENAME -d $LOCAL && \
    ln -sf $LOCAL/apache-maven-$MAVEN_VERSION/bin/mvn $LOCAL/bin
    rm -f $FILENAME
}


function setup_go() {
    GO_URL=https://dl.google.com/go/go$GO_VERSION.$OS-amd64.tar.gz
    FILENAME=$(basename $GO_URL)
    curl -LO $GO_URL && \
    tar -xzf $FILENAME -C $LOCAL && \
    rm -f $FILENAME
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
}

function setup_dbcli() {
    rm -rf ~/.myclirc ~/.config/pgcli
    ln -sf `pwd`/dbcli/myclirc ~/.myclirc
    mkdir -p ~/.config/pgcli
    ln -sf `pwd`/dbcli/pgclirc ~/.config/pgcli/config
}

function setup_git() {
    DIFF_SO_FANCY_URL=https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy
    curl -o $DIFF_SO_FANCY_URL $LOCAL/bin/ && \
    chmod +x $LOCAL/bin/diff-so-fancy
    ln -sf $(pwd)/git/gitconfig ~/.gitconfig
}

function setup_tmux() {
    rm -rf ~/.tmux.conf && \
    ln -sf $(pwd)/tmux/tmux.conf ~/.tmux.conf
}

function setup_zsh() {
    rm -rf ~/.zshrc ~/.oh-my-zsh ~/.zshrc ~/.zshenv ~/.zlogin ~/.zprofile && \
    ln -sf $(pwd)/zsh/zshrc $HOME/.zshrc && \
    ln -sf $(pwd)/zsh/oh-my-zsh $HOME/.oh-my-zsh && \
    ln -sf $(pwd)/zsh/zsh-autosuggestions $HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    ln -sf $(pwd)/zsh/zsh-syntax-highlighting $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting && \
    ln -sf $(pwd)/zsh/themes/nkthanh.zsh-theme $HOME/.oh-my-zsh/custom/themes
    ln -sf $(pwd)/zsh/zlogin $HOME/.zlogin
    ln -sf $sf $(pwd)/zsh/zprofile $HOME/.zprofile
    ln -sf $sf $(pwd)/zsh/zshenv $HOME/.zshenv
    ln -sf $sf $(pwd)/zsh/zshrc $HOME/.zshrc
}

function setup_bash() {
    rm -rf $HOME/.bashrc && ln -sf $(pwd)/bash/bashrc $HOME/.bashrc
}

eval "setup_$1"
