hi ALEWarning      cterm=BOLD ctermbg=NONE ctermfg=NONE      gui=BOLD guibg=NONE guifg=NONE
hi GitGutterAdd    cterm=BOLD ctermbg=NONE ctermfg=green     gui=BOLD guibg=NONE guifg=lightgreen
hi GitGutterDelete cterm=BOLD ctermbg=NONE ctermfg=red       gui=BOLD guibg=NONE guifg=red
hi GitGutterChange cterm=BOLD ctermbg=NONE ctermfg=lightblue gui=BOLD guibg=NONE guifg=lightblue
hi ALEErrorSign    cterm=BOLD ctermbg=NONE ctermfg=red       gui=BOLD guibg=NONE guifg=red
hi ALEWarningSign  cterm=BOLD ctermbg=NONE ctermfg=white     gui=BOLD guibg=NONE guifg=yellow
hi EndOfBuffer     cterm=NONE ctermbg=NONE ctermfg=NONE      gui=NONE guibg=NONE guifg=bg
hi VertSplit       cterm=NONE ctermbg=NONE ctermfg=234       gui=NONE guibg=NONE guifg=grey
hi LineNr          cterm=NONE ctermbg=NONE ctermfg=NONE      gui=NONE guibg=NONE guifg=NONE
