#!/usr/bin/env zsh

export OS=$(uname -s | tr "[:upper:]" "[:lower:]")
export PATH=$HOME/.local/bin:$PATH
export PYTHONDONTWRITEBYTECODE=1
export JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | cut -d'=' -f2 | xargs)
export PATH=$JAVA_HOME/bin:$PATH
export GOPATH=$HOME/workspace/go
export PATH=$HOME/.local/go/bin:$GOPATH:$GOPATH/bin:$PATH
export TERM=xterm-256color
export TERMINFO=/usr/share/terminfo
export PYENV_ROOT="$HOME/.pyenv"
export PATH=$PYENV_ROOT/shims:$PATH
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export FZF_COMPLETION_TRIGGER='~~'
export FZF_COMPLETION_OPTS='+c -x'
export ZSH_CONFIG=$HOME/workspace/dotfiles/zsh
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#6eb579"
