export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="nkthanh"

plugins=(
  vi-mode
  git-prompt
  virtualenv
  git
  mvn
  django
  docker
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $HOME/.fzf.zsh

# Don't create __pycache__ folder
export PYTHONDONTWRITEBYTECODE=1

export TERM=xterm

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Allowing for pipenv to use pyenv                                         
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"
export VIRTUAL_ENV_DISABLE_PROMPT=1

# Setting java and maven
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export JRE_PATH=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre
export M2_HOME=/usr/local/opt/apache-maven-3.6.1
export M2=$M2_HOME/bin
export PATH=$M2:$PATH
export PATH=$HOME/.iterm2:$PATH

# Setting language and encoder
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# =============== Alias =================
alias genssl="openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout cert.key -out cert.crt"
alias -s {yml,yaml,js,ts,jsx,html,txt,c,cpp,java,go,md,json,Dockerfile,gitignore,dockerignore,zsh}=nvim
alias reload="exec \"$SHELL\""
alias md="mkdir"

eval "$(pyenv init -)"
eval "$(pipenv --completion)"
